[project]
name = "raw-llm-quick-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dashscope>=1.25.12",
    "dotenv>=0.9.9",
    "google-genai>=1.60.0",
]
